---
kind: pipeline
name: build
clone:
  depth: 1
volumes:
- name: gopath
  temp: {}
steps:
- name: durl
  image: quay.io/suzuki_shunsuke/durl:1.0.0
  commands:
  - sh scripts/durl.sh
- name: download go modules
  image: golang:1.14.6
  commands:
  - go mod download
  volumes: &volumes
  - name: gopath
    path: /go
- name: golangci-lint
  image: golangci/golangci-lint:v1.29.0-alpine
  commands:
  - golangci-lint run
  volumes: *volumes
- name: benchmark
  image: golang:1.14.6
  commands:
  - cd flute
  - go test -bench=. -benchmem
  volumes: *volumes
- name: test
  image: golang:1.14.7
  commands:
  # bash and cgo seem to be required
  - bash ci/test.sh "$DRONE_REPO_NAME"
  environment:
    CC_TEST_REPORTER_ID:
      from_secret: cc_test_reporter_id
  volumes: *volumes
